### ISSUE TITLE
good！

### ISSUE THREAD

**Issue by mooooon333** [bubble-Q/QiuReader-react#2]

**Comment by mooooon333** [comment]
看了您没有用react那个版本，非常漂亮，但是不知道为什么用react写的这个没有办法运行，是material-ui的版本问题嘛？

**Comment by bubble-Q** [comment]
同学你好，这个项目是很久之前的东西了，现在我克隆到本地发现也跑不起来。问题似乎与 react 相关的依赖相关，现在我也不清楚怎么处理（本人好菜）。如果你是想打开 epub 电子书的话，推荐使用 neat reader。祝好。




------------------ 原始邮件 ------------------
发件人: "Bai"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午1:18
收件人: "bubble-Q/QiuReader-react"<QiuReader-react@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [bubble-Q/QiuReader-react] npm install; npm start后无法运行(Module not found: Error: Cannot resolve module '@babel/runtime/core-js/object/...) (#2)




看了您没有用react那个版本，非常漂亮，但是不知道为什么用react写的这个没有办法运行，是material-ui的版本问题嘛？

**Comment by mooooon333** [comment]
解决啦，是这个原因https://github.com/mui-org/material-ui/issues/12407。谢谢你了，祝好。
